### ISSUE TITLE
Attempting to rematch a trainer that would evolve a pokemon causes a crash

### ISSUE THREAD

**Issue by KingLeonardo** [infinitefusion/infinitefusion-e18#2]
[traceback (1).log](https://github.com/infinitefusion/infinitefusion-e18/files/7697843/traceback.1.log)

Traceback provided.

It seems a comparison between 420 and the given pokemon's species number is happening but failing, likely because the acquired species number is incompatible for the comparison.

**Comment by infinitefusion** [comment]
Fixed
