### ISSUE TITLE
Attempting to open the quick menu in most locations causes a crash

### ISSUE THREAD

**Issue by KingLeonardo** [infinitefusion/infinitefusion-e18#3]
Happens in many places, but has also worked properly at some points.

![145693255-667e7352-856f-41b0-84a4-f0134de46783](https://user-images.githubusercontent.com/11162532/145693860-0577a791-557d-42b2-b01b-69d2b8ec1c7e.png)

**Comment by infinitefusion** [comment]
Fixed
